[project]
site_name = "Rust Package Template Documentation"
site_description = "A GitHub template repository for a Rust package."
site_author = "Isaac C. F. Wong"
copyright = """
Copyright &copy; 2026 Isaac C. F. Wong
"""

nav = [
  { "Get Started" = "index.md" },
  { "API" = [
    { "Overview" = "api/index.md" },
  ] },
  { "Contributing" = "contributing.md" },
  { "Security" = "security.md" },
  { "Template documentation" = [
    { "Overview" = "template_documentation/index.md" },
    { "Using this GitHub template" = [
      { "Template quick start" = "template_documentation/onboarding/quick_start.md" },
      { "Customize and clean up" = "template_documentation/onboarding/customize_repository.md" },
    ] },
    { "User guide" = [
      { "Installation" = "template_documentation/user_guide/installation.md" },
      { "Quick start" = "template_documentation/user_guide/quick_start.md" },
      { "Project structure" = "template_documentation/user_guide/project_structure.md" },
      { "Development tools" = "template_documentation/user_guide/development_tools.md" },
      { "Testing" = "template_documentation/user_guide/testing.md" },
      { "Documentation" = "template_documentation/user_guide/documentation.md" },
      { "CI/CD" = "template_documentation/user_guide/ci_cd.md" },
      { "Packaging" = "template_documentation/user_guide/packaging.md" },
      { "Customization" = "template_documentation/user_guide/customization.md" },
    ] },
    { "Development notes" = [
      { "Code quality" = "template_documentation/development/code_quality.md" },
      { "Changelog" = "template_documentation/development/changelog.md" },
      { "Troubleshooting" = "template_documentation/development/troubleshooting.md" },
    ] },
  ] },
]

[project.theme]
language = "en"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.path",
  "navigation.sections",
  "search.highlight",
  "search.suggest",
  "toc.follow",
]

[repo]
url = "https://github.com/isaac-cf-wong/rust-package-template"
name = "rust-package-template"

[markdown_extensions]
admonition = {}
attr_list = {}
footnotes = {}
md_in_html = {}

[markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[markdown_extensions.pymdownx.superfences]

[plugins]
search = {}
